---
- name: system update
  hosts: host
  become: true
  gather_facts: false

  tasks:
  
    - name: configure additional repos
      yum_repository:
        name: "{{ item.name }}" 
        description: "{{ item.desc }}"
        baseurl: "{{ item.url }}"
        file: redhat
        enabled: true
      loop: "{{ repos }}"