---
- name: system update
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: install software packages
      yum:
        name: "{{ packages }}"
        state: latest
      ignore_errors: true
 

