---
- name: system update
  hosts: host.workbench.lab
  become: true
  gather_facts: false

  tasks:  

    - name: Update all software on system
      yum:
        name: '*'
        state: latest
        update_cache: true
...
