---
- name: enable and start services
  hosts: host.workbench.lab
  become: true
  gather_facts: false

  tasks:

    - name: enable and start services
      service:
        name: "{{ services }}"
        state: started
        enabled: true
      ignore_errors: true
...