---
- name: configure dnf-automatic
  hosts: host
  become: true
  gather_facts: true
    
  tasks:
    - name: set upgrade_type to "{{ upgrade_type }}"
      ansible.builtin.lineinfile:
        path: "{{ dnf_auto_path }}"
        regexp: '^upgrade_type ='
        line: "{{ upgrade_type }}"

    - name: set the name of the system to "{{ ansible_facts['hostname'] }}"
      ansible.builtin.lineinfile:
        path: "{{ dnf_auto_path }}"
        regexp: '^system_name'
        line: system_name = "{{ ansible_facts['hostname'] }}"

#    - name: download and install available updates per type "{{ upgrade_type }}"
#      shell:
#        cmd: systemctl enable dnf-automatic.timer; systemctl start dnf-automatic.timer
...
