---
- name: subscribe and enable correct repos
  gather_facts: false 
  hosts: localhost
  become: true
  vars_files:
    - ./files/rh-acct

  tasks:

    - name: accurately update subscription manager
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        syspurpose:
          usage: "Development/Test"
          role: "Red Hat Enterprise Server"
          service_level_agreement: "Self-Support"
        pool_ids:
          - "{{ ansiblepool }}" 
          - "{{ emplpool }}"
            #  - 8a85f99c727637ad0172e23a149e1195 Ansible
            #  - 8a85f99a73c4701e0173d8c3ecea3aa3 Emp SKU
      register: repos_out

    - name: print subscription output
      debug:
        var: repos_out

    - name: current repos enabled
      command:
        cmd: subscription-manager repos --list-enabled
      register: repos_list

    - name: print enabled repos
        debug:
        var: repos_list.stdout_lines
...
