---
- name: system update
  hosts: host
  become: true
  gather_facts: false
  vars_files:
    - files/packages.yml

  tasks:
    - name: install software packages
      yum:
        name: "{{ item.name }}"
        state: latest
      loop: "{{ packages }}"
    
    - name: Update all software on system
      yum:
        name: '*'
        state: latest
...
