---
- name: configure additional repos
  yum_repository:
    name: "{{ item.name }}" 
    description: "{{ item.desc }}"
    baseurl: "{{ item.url }}"
    file: redhat
    enabled: true
  loop: "{{ repos }}"