---
- name: configure additional repos
  yum_repository:
    name: "{{ item.id }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.url }}"
    file: redhat
    enabled: "{{ item.enabled }}"
  loop: "{{ repos }}"



