---
- name: ensure dnf-automatic is installed
  yum:
    name: dnf-automatic
    state: present

- name: set upgrade_type to "{{ upgrade_type }}"
  lineinfile:
    path: "{{ dnf_auto_path }}"
    regexp: '^upgrade_type ='
    line: "{{ upgrade_type }}"

- name: set the name of the system to "{{ ansible_facts['hostname'] }}"
  lineinfile:
    path: "{{ dnf_auto_path }}"
    regexp: '^system_name'
    line: system_name = "{{ ansible_facts['hostname'] }}"

- name: download and install available updates per type "{{ upgrade_type }}"
  shell:
    cmd: systemctl enable dnf-automatic-install.timer && systemctl start dnf-automatic-install.timer
...
