---
- name: install rear software
  yum:
    name: "{{ rear }}"
    state: latest

- name: produce bootable image
  shell:
    cmd: rear mkrescue -v

- name: print available images
  command:
    cmd: ls -l /var/lib/rear/output/rear*
...
