---
packages:
- cockpit
- cockpit-composer
- cockpit-dashboard
- cockpit-machines
- cockpit-packagekit
- cockpit-pcp
- cockpit-podman
- cockpit-session-recording
- rhel-system-roles
- redhat-support-tool
- sshpass
- ansible
- git

backup:
- dnf-automatic

rear:
- genisoimage 
- rear 
- syslinux 
- crash 
- sos 

virtual:
- virt-install
- virt-viewer
- libvirt-nss
- libvirt-daemon-config-network

crc:
- dnf
- haproxy
- policycoreutils-python-utils
- setroubleshoot-server
...
