---
partitions:
    - number: 4
      start: 82GB
      end: 100%
      name: vmstore
      label: gpt
      flag: [ lvm ]
      unit: GB

volume_groups:
    - name: vmstore
      dev: /dev/nvme0n1p4

logical_volumes:
    - lv_name: tower
      size: 100g
      fstype: xfs
      vg_name: vmstore
      mount_path: /mnt/tower
